title: Ziad Demir
logo: /assets/img/ziad.png
description: Ziad is a Game Developer and BA Student at Cologne Game Lab based in Germany.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
