title: Ziad Demir
logo: /assets/img/ziad.png
description: Game Dev
bio1: Ziad is a Game Developer and Cologne Game Lab BA Student based in Germany.
bio2: Interested in skill-based systems, expressive mechanics and games history. Always prototyping new ideas.
skills: Godot / Unity / Logic Pro / Final Cut Pro / Pixel Art & Hip-Hop
show_downloads: false
show_github: false
google_analytics:
theme: jekyll-theme-minimal
